import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

/**
 * Creating a sidebar enables you to:
 *
 * - Create an ordered group of docs
 * - Render a sidebar for each doc of that group
 * - Provide next/previous navigation.
 *
 * The sidebars can be generated from the filesystem, or explicitly defined
 * here.
 *
 * Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
	// By default, Docusaurus generates a sidebar from the docs folder structure
	tutorialSidebar: [{ dirName: ".", type: "autogenerated" }],

	// But you can create a sidebar manually
	//
	// tutorialSidebar: [
	// 'intro',
	// 'hello',
	// {
	//     type: 'category',
	//     label: 'Tutorial',
	//     items: ['tutorial-basics/create-a-document'],
	// },
	// ],
	//
};

export default sidebars;
