name: Release

on:
  pull_request:
    types:
      - closed
    branches:
      - main
    paths:
      - 'src/**/*'
      - assets
      - build.project.json
      - mantle.yaml
      - package.json
  workflow_dispatch:

permissions:
  contents: write
  packages: write

concurrency:
  group: production_environment
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4

      - name: Install pnpm
        uses: pnpm/action-setup@v3

      - name: Use Node.js 20
        uses: actions/setup-node@1e60f620b9541d16bece96c5465dc8ee9832be0b # v4
        with:
          node-version: 20
          cache: pnpm

      - name: Install dependencies
        run: pnpm install --prod

      - name: Install roblox-ts
        run: pnpm add roblox-ts

      - name: Setup Rokit
        uses: CompeyDev/setup-rokit@a13c97e4a1f72bc90e106bf044118fea3e341ffb # v0.1.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Compile
        run: pnpm prod:build --verbose

      - name: Build project
        run: rojo build ./build.project.json --output place.rbxlx

      - name: Upload place
        uses: actions/upload-artifact@834a144ee995460fba8ed112a2fc961b36a5ec5a # v4
        with:
          name: place
          path: place.rbxlx
          if-no-files-found: error

  deploy:
    runs-on: self-hosted
    environment: production
    needs: build

    steps:
      - name: Install GH CLI
        uses: dev-hanz-ops/install-gh-cli-action@8fff9050dae2d81b38f94500d8b74ad1d1d47410 # v0.2.0

      - name: Setup Rokit
        uses: CompeyDev/setup-rokit@a13c97e4a1f72bc90e106bf044118fea3e341ffb # v0.1.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Download place artifact
        uses: actions/download-artifact@fa0a91b85d4f404e444e00e005971372dc801d16 # v4
        with:
          name: place

      - name: Deploy game
        run: mantle deploy mantle.yaml --allow-purchases --environment production
        env:
          ROBLOSECURITY: ${{ secrets.ROBLOSECURITY }}
          MANTLE_AWS_ACCESS_KEY_ID: ${{ secrets.MANTLE_AWS_ACCESS_KEY_ID }}
          MANTLE_AWS_SECRET_ACCESS_KEY: ${{ secrets.MANTLE_AWS_SECRET_ACCESS_KEY }}

  tag:
    runs-on: ubuntu-latest
    needs: deploy
    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4
      - name: Bump version and push tag
        id: tag_version
        uses: mathieudutour/github-tag-action@a22cf08638b34d5badda920f9daf6e72c477b07b # v6.2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Download place artifact
        uses: actions/download-artifact@fa0a91b85d4f404e444e00e005971372dc801d16 # v4
        with:
          name: place

      - name: Create a GitHub release
        uses: ncipollo/release-action@2c591bcc8ecdcd2db72b97d6147f871fcd833ba5 # v1
        with:
          tag: ${{ steps.tag_version.outputs.new_tag }}
          name: Release ${{ steps.tag_version.outputs.new_tag }}
          body: ${{ steps.tag_version.outputs.changelog }}
          artifacts: place.rbxlx
