name: Release

on:
  pull_request:
    types:
      - closed
    branches:
      - main
    paths:
      - 'src/**/*'
      - build.project.json
      - mantle.yml
      - package.json
  workflow_dispatch:
    inputs:
      version:
        type: string
        required: true
        description: Version to release

permissions:
  contents: write
  packages: write

concurrency:
  group: production_environment
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4

      - name: Install pnpm
        uses: pnpm/action-setup@v3

      - name: Use Node.js 20
        uses: actions/setup-node@1e60f620b9541d16bece96c5465dc8ee9832be0b # v4
        with:
          node-version: 20
          cache: pnpm

      - name: Install dependencies
        run: pnpm install --prod

      - name: Install roblox-ts
        run: pnpm add roblox-ts

      - name: Setup Aftman
        uses: ok-nick/setup-aftman@e226f24209f47677da7b215bab44f6351a2c043b # v0.4.2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Compile
        run: pnpm build-prod --verbose

      - name: Build project
        run: rojo build ./build.project.json --output place.rbxlx

      - name: Upload place
        uses: actions/upload-artifact@0b2256b8c012f0828dc542b3febcab082c67f72b # v4
        with:
          name: place
          path: place.rbxlx
          if-no-files-found: error

  deploy:
    runs-on: self-hosted
    environment: production
    needs: build

    steps:
      - name: Install GH CLI
        uses: dev-hanz-ops/install-gh-cli-action@8fff9050dae2d81b38f94500d8b74ad1d1d47410 # v0.2.0

      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4
      - uses: ok-nick/setup-aftman@e226f24209f47677da7b215bab44f6351a2c043b # v0.4.2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Download place artifact
        uses: actions/download-artifact@fa0a91b85d4f404e444e00e005971372dc801d16 # v4
        with:
          name: place

      - name: Deploy game
        run: mantle deploy --allow-purchases --environment production
        env:
          ROBLOSECURITY: ${{ secrets.ROBLOSECURITY }}
          MANTLE_AWS_ACCESS_KEY_ID: ${{ secrets.MANTLE_AWS_ACCESS_KEY_ID }}
          MANTLE_AWS_SECRET_ACCESS_KEY: ${{ secrets.MANTLE_AWS_SECRET_ACCESS_KEY }}

  release_workflow:
    runs-on: ubuntu-latest
    needs: deploy
    steps:
      - name: GitFlow workflow action - Release workflows
        uses: hoangvvo/gitflow-workflow-action@0.3.7
        with:
          develop_branch: develop
          main_branch: main
          merge_back_from_main: false
          version: ${{ inputs.version }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
