name: Release Develop

on:
  push:
    branches:
      - develop
    paths:
      - 'src/**/*'
      - default.project.json
      - mantle.yaml
      - package.json
  workflow_dispatch:

permissions:
  contents: write
  packages: write

concurrency:
  group: development_environment
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4

      - name: Install pnpm
        uses: pnpm/action-setup@v3

      - name: Use Node.js 20
        uses: actions/setup-node@1e60f620b9541d16bece96c5465dc8ee9832be0b # v4
        with:
          node-version: 20
          cache: pnpm

      - name: Install dependencies
        run: pnpm install --prod

      - name: Install roblox-ts
        run: pnpm add roblox-ts

      - name: Setup Aftman
        uses: ok-nick/setup-aftman@e226f24209f47677da7b215bab44f6351a2c043b # v0.4.2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Compile
        run: npx rbxtsc --verbose

      - name: Build project
        run: rojo build ./default.project.json --output place.rbxlx

      - name: Upload place
        uses: actions/upload-artifact@89ef406dd8d7e03cfd12d9e0a4a378f454709029 # v4
        with:
          name: place
          path: place.rbxlx
          if-no-files-found: error

  deploy:
    runs-on: self-hosted
    environment: development
    needs: build

    steps:
      - name: Install GH CLI
        uses: dev-hanz-ops/install-gh-cli-action@8fff9050dae2d81b38f94500d8b74ad1d1d47410 # v0.2.0

      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4
      - uses: ok-nick/setup-aftman@e226f24209f47677da7b215bab44f6351a2c043b # v0.4.2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Download place artifact
        uses: actions/download-artifact@fa0a91b85d4f404e444e00e005971372dc801d16 # v4
        with:
          name: place

      - name: Deploy place
        run: mantle deploy mantle.yaml --environment development
        env:
          ROBLOSECURITY: ${{ secrets.ROBLOSECURITY }}
          MANTLE_AWS_ACCESS_KEY_ID: ${{ secrets.MANTLE_AWS_ACCESS_KEY_ID }}
          MANTLE_AWS_SECRET_ACCESS_KEY: ${{ secrets.MANTLE_AWS_SECRET_ACCESS_KEY }}
