name: Release Develop

on:
  push:
    branches:
      - develop
    paths:
      - 'src/**/*'
      - default.project.json
      - mantle.yaml
      - package.json
  workflow_dispatch:

permissions:
  contents: write
  packages: write

concurrency:
  group: development_environment
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4

      - name: Install pnpm
        uses: pnpm/action-setup@v3

      - name: Use Node.js 20
        uses: actions/setup-node@1e60f620b9541d16bece96c5465dc8ee9832be0b # v4
        with:
          node-version: 20
          cache: pnpm

      - name: Install dependencies
        run: pnpm install --prod

      - name: Install roblox-ts
        run: pnpm add roblox-ts

      - name: Setup Rokit
        uses: CompeyDev/setup-rokit@d49be92bd9502180218c3f43e7988faa945217b0 # v0.1.2

      - name: Compile
        run: npx rbxtsc --verbose

      - name: Build project
        run: rojo build ./default.project.json --output place.rbxlx

      - name: Upload place
        uses: actions/upload-artifact@834a144ee995460fba8ed112a2fc961b36a5ec5a # v4
        with:
          name: place
          path: place.rbxlx
          if-no-files-found: error

  deploy:
    runs-on: ubuntu-latest
    environment: development
    needs: build

    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4

      - name: Setup Rokit
        uses: CompeyDev/setup-rokit@d49be92bd9502180218c3f43e7988faa945217b0 # v0.1.2

      - name: Download place artifact
        uses: actions/download-artifact@fa0a91b85d4f404e444e00e005971372dc801d16 # v4
        with:
          name: place

      # As ROBLOSECURITY keys are region locked, we need to use a VPN to ensure
      # the github actions runner is in the same region as our Roblox account.
      - name: Easy WireGuard Connection
        uses: niklaskeerl/easy-wireguard-action@v2
        with:
          WG_CONFIG_FILE: ${{ secrets.WG_CONFIG_FILE }}

      # - name: Poll for IP Change
      #   run: |
      #     $elapsed = 0
      #     while ($true) {
      #       try {
      #         $response = Invoke-WebRequest -Uri 'https://httpbin.org/ip' -Method GET -UseBasicParsing
      #         $content = ConvertFrom-Json $response.Content
      #         if ($content.origin -eq "159.223.100.103") {
      #           break
      #         }
      #       } catch {}
      #       if ($elapsed -ge 20) {
      #         Write-Error "Timeout reached!"
      #         exit 1
      #       }
      #       Write-Output "Polling.. Elasped: $elapsed, IP: $($content.origin)"
      #       Start-Sleep 5
      #       $elapsed += 5
      #     }
      #     Write-Output "Success!"

      - name: Deploy place
        run: mantle deploy mantle.yaml --environment development
        env:
          ROBLOSECURITY: ${{ secrets.ROBLOSECURITY }}
          MANTLE_OPEN_CLOUD_API_KEY: ${{ secrets.MANTLE_OPEN_CLOUD_API_KEY }}
          MANTLE_AWS_ACCESS_KEY_ID: ${{ secrets.MANTLE_AWS_ACCESS_KEY_ID }}
          MANTLE_AWS_SECRET_ACCESS_KEY: ${{ secrets.MANTLE_AWS_SECRET_ACCESS_KEY }}
